[DEBUG] 2020-11-18 19:12:49,696 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:12:49,931 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:13:50,005 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:13:50,177 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:14:50,253 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:14:50,403 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:15:50,482 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:15:50,683 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:16:50,768 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:16:50,943 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:17:51,019 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:17:51,176 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:18:51,251 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:18:51,414 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:19:51,491 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:19:51,649 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:20:51,735 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:20:51,961 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:21:52,039 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:21:52,164 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:22:52,237 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:22:52,372 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:23:52,455 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:23:52,654 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:24:52,722 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:24:53,017 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:25:53,099 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:25:53,278 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:26:53,356 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:26:53,565 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-18 19:27:46,248 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.doctor_api.get_users_list"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 214, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anil/medley/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/anil/medley/apps/erpnext/erpnext/doctor_api.py", line 18
    users = frappe.db.get_all('Doctor',fields=['doctor_name','specialisation']])
                                                                              ^
SyntaxError: closing parenthesis ']' does not match opening parenthesis '('
[ERROR] 2020-11-18 19:27:46,414 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-18 19:27:46.249245-127.0.0.1-49d
[DEBUG] 2020-11-18 19:27:53,638 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:27:53,814 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:28:53,890 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:28:54,133 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:29:54,199 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:29:54,343 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:30:54,408 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:30:54,647 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:31:54,716 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:31:54,881 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:33:12,209 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:33:24,703 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:34:25,175 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:34:26,093 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:35:26,169 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:35:26,347 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:36:26,417 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:36:26,693 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:37:26,764 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:37:26,936 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-18 19:38:04,296 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.doctor_api.get_users_list"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 214, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.doctor_api' has no attribute 'get_users_list'
[ERROR] 2020-11-18 19:38:05,304 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-18 19:38:04.298790-127.0.0.1-fed
[DEBUG] 2020-11-18 19:38:27,008 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:38:27,452 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:39:27,523 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:39:27,727 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:40:27,812 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:40:28,096 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:41:28,160 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:41:28,323 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:42:28,401 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:42:28,587 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:43:28,663 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:43:28,824 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:44:28,887 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:44:29,092 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:45:29,157 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:45:29,285 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:46:29,358 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:46:29,510 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:47:29,578 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:47:29,690 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:48:29,769 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:48:30,090 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:49:30,162 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:49:30,349 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:50:30,424 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:50:30,663 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:51:30,730 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:51:30,834 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:52:30,910 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:52:31,177 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:53:31,251 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:53:31,426 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:54:31,495 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:54:31,612 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:55:31,681 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:55:31,826 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:56:31,894 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:56:32,134 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 19:57:32,205 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:57:32,356 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-18 19:58:11,791 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.doctor_api.get_users_list"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 214, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anil/medley/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/anil/medley/apps/erpnext/erpnext/doctor_api.py", line 19
    print(type(doctor_details))
                              ^
IndentationError: unindent does not match any outer indentation level
[ERROR] 2020-11-18 19:58:12,002 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-18 19:58:11.793852-127.0.0.1-9d5
[DEBUG] 2020-11-18 19:58:32,429 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:58:32,592 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-18 19:58:42,173 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.doctor_api.get_users_list"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 214, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/anil/medley/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/anil/medley/apps/erpnext/erpnext/doctor_api.py", line 19
    print(type(doctor_details))
                              ^
IndentationError: unindent does not match any outer indentation level
[ERROR] 2020-11-18 19:58:42,502 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-18 19:58:42.173912-127.0.0.1-8e6
[ERROR] 2020-11-18 19:59:01,818 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.doctor_api.get_users_list"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    raise e
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 49, in execute_cmd
    method = get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 214, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.doctor_api' has no attribute 'get_users_list'
[ERROR] 2020-11-18 19:59:01,933 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-18 19:59:01.819405-127.0.0.1-5b3
[DEBUG] 2020-11-18 19:59:32,665 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 19:59:32,836 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:00:32,910 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:00:33,216 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-18 20:00:34,635 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.doctor_api.get_doctor_list"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/doctor_api.py", line 20, in get_doctor_list
    print(type(json(doctor_details)))
TypeError: 'module' object is not callable
[ERROR] 2020-11-18 20:00:34,761 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-18 20:00:34.636979-127.0.0.1-9d8
[DEBUG] 2020-11-18 20:01:33,293 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:01:33,504 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:02:33,578 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:02:33,847 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:03:33,909 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:03:34,112 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:04:34,183 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:04:34,439 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:05:34,521 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:05:34,733 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:06:34,805 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:06:34,978 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:07:35,038 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:07:35,162 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:08:35,217 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:08:35,420 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:09:35,486 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:09:35,709 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:10:35,775 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:10:35,906 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:11:35,978 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:11:36,167 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:12:36,230 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:12:36,457 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:13:36,528 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:13:36,681 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:14:36,754 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:14:36,924 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:15:36,997 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:15:37,233 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:16:37,302 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:16:37,503 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:17:37,573 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:17:37,714 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:18:37,783 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:18:37,930 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:19:37,991 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:19:38,146 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:20:38,221 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:20:38,511 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:21:38,575 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:21:38,710 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:22:38,784 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:22:38,996 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:23:39,066 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:23:39,268 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:24:39,340 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:24:39,711 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:25:39,773 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:25:39,935 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:26:39,999 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:26:40,142 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:27:40,203 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:27:40,306 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:28:40,379 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:28:40,646 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:29:40,722 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:29:40,897 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:30:40,967 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:30:41,147 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:31:41,214 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:31:41,346 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:32:41,415 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:32:41,671 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:33:41,745 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:33:41,994 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:34:42,067 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:34:42,211 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:35:42,282 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:35:42,460 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:36:42,527 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:36:42,701 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:37:42,768 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:37:42,958 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:38:43,036 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:38:43,234 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:39:43,304 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:39:43,479 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:40:43,556 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:40:43,912 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:41:43,987 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:41:44,315 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-18 20:42:44,388 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-18 20:42:44,533 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:06:21,349 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:06:21,682 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:07:21,749 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:07:21,855 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:08:21,917 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:08:22,083 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:09:22,156 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:09:22,324 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:10:22,387 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:10:22,493 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:11:22,556 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:11:22,665 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:12:22,726 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:12:22,926 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:13:23,014 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:13:23,178 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:14:23,246 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:14:23,447 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:15:23,506 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:15:23,651 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:16:23,720 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:16:23,928 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:17:23,995 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:17:24,174 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:18:24,240 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:18:24,392 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:19:24,470 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:19:24,625 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:20:24,695 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:20:24,878 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:21:24,945 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:21:25,059 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:22:25,128 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:22:25,261 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:23:25,330 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:23:25,528 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:23:52,853 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-20 11:23:52,960 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:23:52.855207-127.0.0.1-e53
[ERROR] 2020-11-20 11:26:59,843 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-20 11:26:59,958 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:26:59.843943-127.0.0.1-97a
[DEBUG] 2020-11-20 11:27:56,896 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:27:57,072 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:28:57,601 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:28:58,204 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:29:58,276 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:29:58,529 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:30:35,424 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-20 11:30:35,590 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:30:35.426705-127.0.0.1-6c9
[ERROR] 2020-11-20 11:31:00,812 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-11-20 11:31:00,898 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:31:00.813018-127.0.0.1-bae
[DEBUG] 2020-11-20 11:31:59,188 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:31:59,340 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:32:59,417 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:32:59,742 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:33:59,811 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:33:59,941 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:35:00,014 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:35:00,162 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:36:00,235 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:36:00,554 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:37:00,628 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:37:00,762 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:38:00,831 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:38:00,959 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:39:01,029 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:39:01,240 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:39:09,329 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.selling.page.point_of_sale.point_of_sale.get_items",
 "item_group": "All Item Groups",
 "page_length": "40",
 "search_value": "",
 "start": "0"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_items() missing 1 required positional argument: 'price_list'
[ERROR] 2020-11-20 11:39:09,344 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:39:09.331261-127.0.0.1-571
[ERROR] 2020-11-20 11:39:10,514 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Invoice",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:39:10,606 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:39:10.517056-127.0.0.1-cf8
[ERROR] 2020-11-20 11:39:29,830 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.accounts.party.get_party_details",
 "company": "Medley",
 "currency": "INR",
 "doctype": "Sales Invoice",
 "party": "bharat",
 "party_type": "Customer",
 "pos_profile": "Medley Pos",
 "posting_date": "2020-11-20"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/accounts/party.py", line 32, in get_party_details
    return _get_party_details(party, account, party_type,
  File "/home/anil/medley/apps/erpnext/erpnext/accounts/party.py", line 49, in _get_party_details
    party_address, shipping_address = set_address_details(party_details, party, party_type, doctype, company, party_address, company_address, shipping_address)
  File "/home/anil/medley/apps/erpnext/erpnext/accounts/party.py", line 104, in set_address_details
    get_regional_address_details(party_details, doctype, company)
  File "/home/anil/medley/apps/erpnext/erpnext/__init__.py", line 129, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:39:29,840 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:39:29.831722-127.0.0.1-cf6
[DEBUG] 2020-11-20 11:40:01,315 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:40:01,554 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:41:01,628 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:41:01,750 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:42:01,821 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:42:01,982 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:43:02,052 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:43:02,204 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:44:02,279 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:44:02,509 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:45:02,580 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:45:02,756 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:45:41,068 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Invoice",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:45:41,082 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:45:41.069984-127.0.0.1-f43
[DEBUG] 2020-11-20 11:46:02,821 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:46:03,166 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:47:03,243 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:47:03,393 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:47:37,300 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Order",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\",\"tax_category\":\"Gst\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:47:37,308 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:47:37.301353-127.0.0.1-28b
[DEBUG] 2020-11-20 11:48:03,457 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:48:03,622 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:49:03,691 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:49:03,886 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:50:03,949 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:50:04,043 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:51:04,112 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:51:04,261 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:52:04,329 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:52:05,210 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:53:05,272 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:53:05,937 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:53:07,346 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "frappe.desk.notifications.get_open_count",
 "doctype": "Company",
 "items": "[\"Quotation\",\"Sales Order\",\"Delivery Note\",\"Sales Invoice\",\"Issue\",\"Project\"]",
 "name": "Medley"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 536, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/anil/medley/apps/frappe/frappe/desk/notifications.py", line 248, in get_open_count
    total = len(frappe.get_all(d, fields="name",
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1327, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1300, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/anil/medley/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/anil/medley/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/anil/medley/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/anil/medley/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/anil/medley/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Delivery Note')
[ERROR] 2020-11-20 11:53:07,474 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:53:07.463061-127.0.0.1-98f
[DEBUG] 2020-11-20 11:54:06,007 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:54:06,587 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[ERROR] 2020-11-20 11:54:17,301 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Invoice",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:54:17,320 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:54:17.303634-127.0.0.1-057
[ERROR] 2020-11-20 11:54:57,169 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Invoice",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\",\"customer\":\"\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:54:57,179 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:54:57.170382-127.0.0.1-b9a
[ERROR] 2020-11-20 11:55:05,516 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.accounts.party.get_party_details",
 "company": "Medley",
 "currency": "INR",
 "doctype": "Sales Invoice",
 "party": "bharat",
 "party_type": "Customer",
 "pos_profile": "Medley Pos",
 "posting_date": "2020-11-20",
 "price_list": "Medicines"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/accounts/party.py", line 32, in get_party_details
    return _get_party_details(party, account, party_type,
  File "/home/anil/medley/apps/erpnext/erpnext/accounts/party.py", line 49, in _get_party_details
    party_address, shipping_address = set_address_details(party_details, party, party_type, doctype, company, party_address, company_address, shipping_address)
  File "/home/anil/medley/apps/erpnext/erpnext/accounts/party.py", line 104, in set_address_details
    get_regional_address_details(party_details, doctype, company)
  File "/home/anil/medley/apps/erpnext/erpnext/__init__.py", line 129, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-20 11:55:05,532 | /home/anil/medley/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-11-20 11:55:05.519434-127.0.0.1-c9f
[DEBUG] 2020-11-20 11:55:06,657 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:55:07,948 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:56:08,009 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:56:08,271 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:57:08,333 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:57:08,464 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:58:08,537 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:58:08,709 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 11:59:08,766 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 11:59:08,861 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:00:08,933 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:00:09,196 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:01:09,266 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:01:09,409 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:02:09,480 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:02:09,582 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:03:09,651 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:03:09,773 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:04:09,845 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:04:09,996 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:05:10,066 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:05:10,217 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:06:10,288 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:06:10,422 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:07:10,494 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:07:10,624 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:08:10,689 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:08:10,867 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:09:10,928 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:09:11,040 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:10:11,106 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:10:11,240 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:11:11,301 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:11:11,426 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:12:11,502 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:12:11,726 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:13:11,790 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:13:11,925 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:14:11,995 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:14:12,117 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:15:12,180 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:15:12,558 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:16:12,631 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:16:12,784 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:17:12,859 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:17:13,002 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:18:13,077 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:18:13,247 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:19:13,307 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:19:13,448 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:20:13,514 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:20:13,732 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:21:13,795 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:21:13,903 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:22:13,973 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:22:14,136 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:23:14,206 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:23:14,414 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:24:14,487 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:24:14,730 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:25:14,790 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:25:14,911 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:26:14,978 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:26:15,108 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:27:15,172 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:27:15,285 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:28:15,356 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:28:15,548 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:29:15,617 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:29:15,769 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:30:15,835 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:30:15,961 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:31:16,030 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:31:16,174 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:32:16,340 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:32:16,576 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:33:16,641 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:33:16,735 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:34:16,803 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:34:16,929 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:35:17,000 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:35:17,137 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:36:17,217 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:36:17,460 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:37:17,529 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:37:17,653 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:38:17,712 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:38:17,824 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:39:17,894 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:39:18,035 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:40:18,103 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:40:18,333 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:41:18,401 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:41:18,565 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:42:18,627 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:42:18,760 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:43:18,819 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:43:18,961 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:44:19,039 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:44:19,283 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:45:19,353 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:45:19,491 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:46:19,551 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:46:19,690 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:47:19,760 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:47:19,894 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:48:19,969 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:48:20,201 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:49:20,268 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
[DEBUG] 2020-11-20 12:49:20,401 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicines
Queued events for site ordermedicines
[DEBUG] 2020-11-20 12:50:20,466 | /home/anil/medley/apps/frappe/frappe/utils/scheduler.py:
Site: ordermedicine
Access denied for site ordermedicine
